# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StackTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StackTest

  target 'StackTestTests' do
    inherit! :search_paths
    # Pods for testing
	pod ‘Kiwi’
  end

  target 'StackTestUITests' do
    inherit! :search_paths
    # Pods for testing
	
  end

end
